import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { createKeyPairSignerFromBytes, createKeyPairSignerFromPrivateKeyBytes, getAddressEncoder } from '@solana/kit';

/** Default payer location: outside the repo, one file per cluster. */
export function defaultKeypairPath(cluster) {
  return join(homedir(), '.config', 'solana-launch-intel', `${cluster}-payer.json`);
}

/** Refuse keypair paths inside the repository working tree. */
function assertOutsideRepo(path, repoRoot) {
  const abs = resolve(path);
  if (repoRoot && (abs === resolve(repoRoot) || abs.startsWith(resolve(repoRoot) + '/'))) {
    throw new Error(`Refusing to use a keypair inside the repository (${abs}). Keep keys outside the working tree.`);
  }
}

/**
 * Load a Solana CLI-format keypair (JSON array of 64 bytes). Only for devnet
 * and testnet is a missing file generated; mainnet keys must be supplied
 * explicitly (and should live in a hardware wallet or Squads vault).
 */
export async function loadOrCreatePayer({ path, cluster, repoRoot }) {
  assertOutsideRepo(path, repoRoot);
  if (existsSync(path)) {
    const bytes = Uint8Array.from(JSON.parse(readFileSync(path, 'utf8')));
    return { signer: await createKeyPairSignerFromBytes(bytes), created: false };
  }
  if (cluster === 'mainnet-beta') {
    throw new Error(`No keypair at ${path}. Mainnet keys are never generated by this tool.`);
  }
  const seed = crypto.getRandomValues(new Uint8Array(32));
  const signer = await createKeyPairSignerFromPrivateKeyBytes(seed);
  const pub = getAddressEncoder().encode(signer.address);
  mkdirSync(dirname(path), { recursive: true, mode: 0o700 });
  writeFileSync(path, JSON.stringify([...seed, ...pub]), { mode: 0o600 });
  chmodSync(path, 0o600);
  // Re-load from disk so a bad write fails here, not mid-launch.
  const reloaded = await createKeyPairSignerFromBytes(Uint8Array.from(JSON.parse(readFileSync(path, 'utf8'))));
  if (reloaded.address !== signer.address) throw new Error('Keypair round-trip mismatch');
  return { signer: reloaded, created: true };
}
